__asm__ __volatile__("# GNU C++ (SUSE Linux) version 4.4.1 [gcc-4_4-branch revision 150839] (x86_64-suse-linux)\n\t"
"#	compiled by GNU C version 4.4.1 [gcc-4_4-branch revision 150839], GMP version 4.3.1, MPFR version 2.4.1-p5.\n\t"
"# GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072\n\t"
"# options passed:  -imultilib 32 -D_GNU_SOURCE D4.cpp -m32 -mtune=generic\n\t"
"# -march=i586 -auxbase-strip D4_S.cpp -O3 -fverbose-asm -fno-ident\n\t"
"# options enabled:  -falign-loops -fargument-alias -fauto-inc-dec\n\t"
"# -fbranch-count-reg -fcaller-saves -fcommon -fcprop-registers\n\t"
"# -fcrossjumping -fcse-follow-jumps -fdefer-pop\n\t"
"# -fdelete-null-pointer-checks -fdwarf2-cfi-asm -fearly-inlining\n\t"
"# -feliminate-unused-debug-types -fexceptions -fexpensive-optimizations\n\t"
"# -fforward-propagate -ffunction-cse -fgcse -fgcse-after-reload -fgcse-lm\n\t"
"# -fguess-branch-probability -fif-conversion -fif-conversion2\n\t"
"# -findirect-inlining -finline -finline-functions\n\t"
"# -finline-functions-called-once -finline-small-functions -fipa-cp\n\t"
"# -fipa-cp-clone -fipa-pure-const -fipa-reference -fira-share-save-slots\n\t"
"# -fira-share-spill-slots -fivopts -fkeep-static-consts\n\t"
"# -fleading-underscore -fmath-errno -fmerge-constants -fmerge-debug-strings\n\t"
"# -fmove-loop-invariants -foptimize-register-move -foptimize-sibling-calls\n\t"
"# -fpcc-struct-return -fpeephole -fpeephole2 -fpredictive-commoning\n\t"
"# -fregmove -freorder-blocks -freorder-functions -frerun-cse-after-loop\n\t"
"# -fsched-interblock -fsched-spec -fsched-stalled-insns-dep\n\t"
"# -fschedule-insns2 -fsigned-zeros -fsplit-ivs-in-unroller\n\t"
"# -fsplit-wide-types -fstrict-aliasing -fstrict-overflow -fthread-jumps\n\t"
"# -ftoplevel-reorder -ftrapping-math -ftree-builtin-call-dce -ftree-ccp\n\t"
"# -ftree-ch -ftree-copy-prop -ftree-copyrename -ftree-cselim -ftree-dce\n\t"
"# -ftree-dominator-opts -ftree-dse -ftree-fre -ftree-loop-im\n\t"
"# -ftree-loop-ivcanon -ftree-loop-optimize -ftree-parallelize-loops=\n\t"
"# -ftree-pre -ftree-reassoc -ftree-scev-cprop -ftree-sink -ftree-sra\n\t"
"# -ftree-switch-conversion -ftree-ter -ftree-vect-loop-version\n\t"
"# -ftree-vectorize -ftree-vrp -funit-at-a-time -funswitch-loops\n\t"
"# -fvect-cost-model -fverbose-asm -fzero-initialized-in-bss -m32 -m80387\n\t"
"# -m96bit-long-double -maccumulate-outgoing-args -malign-stringops\n\t"
"# -mfancy-math-387 -mfp-ret-in-387 -mfused-madd -mglibc -mieee-fp\n\t"
"# -mno-red-zone -mno-sse4 -mpush-args -msahf -mtls-direct-seg-refs\n\t"
"\n\t"
"# Compiler executable checksum: 9324fd3305365d6cc397a0043b4bc055\n\t"
"\n\t"
"	.text\n\t"
"	.p2align 4,,15\n\t"
".globl _Z3LCSiiii\n\t"
"	.type	_Z3LCSiiii, @function\n\t"
"_Z3LCSiiii:\n\t"
".LFB400:\n\t"
"	.cfi_startproc\n\t"
"	.cfi_personality 0x0,__gxx_personality_v0\n\t"
"	pushl	%ebp	#\n\t"
"	.cfi_def_cfa_offset 8\n\t"
"	movl	%esp, %ebp	#,\n\t"
"	.cfi_offset 5, -8\n\t"
"	.cfi_def_cfa_register 5\n\t"
"	pushl	%edi	#\n\t"
"	pushl	%esi	#\n\t"
"	pushl	%ebx	#\n\t"
"	subl	$108, %esp	#,\n\t"
"	movl	16(%ebp), %esi	# PB, PB\n\t"
"	.cfi_offset 3, -20\n\t"
"	.cfi_offset 6, -16\n\t"
"	.cfi_offset 7, -12\n\t"
"	movl	20(%ebp), %eax	# KB, tmp124\n\t"
"	subl	%esi, %eax	# PB, tmp124\n\t"
"	cmpl	$1, %eax	#, tmp124\n\t"
"	je	.L49	#,\n\t"
"	movl	12(%ebp), %ecx	# KA,\n\t"
"	subl	8(%ebp), %ecx	# PA,\n\t"
"	movl	%ecx, -72(%ebp)	#, %sfp\n\t"
"	jne	.L50	#,\n\t"
".L3:\n\t"
"	xorl	%ebx, %ebx	# q\n\t"
".L7:\n\t"
"	addl	$108, %esp	#,\n\t"
"	movl	%ebx, %eax	# q,\n\t"
"	popl	%ebx	#\n\t"
"	popl	%esi	#\n\t"
"	popl	%edi	#\n\t"
"	popl	%ebp	#\n\t"
"	ret\n\t"
".L50:\n\t"
"	sall	$2, %ecx	#,\n\t"
"	movl	%ecx, -48(%ebp)	#, %sfp\n\t"
"	movl	%ecx, (%esp)	#,\n\t"
"	call	_Znaj	#\n\t"
"	movl	-48(%ebp), %ebx	# %sfp,\n\t"
"	movl	%ebx, (%esp)	#,\n\t"
"	movl	%eax, LCSP	# D.9076, LCSP\n\t"
"	call	_Znaj	#\n\t"
"	movl	8(%ebp), %edx	# PA,\n\t"
"	movl	-72(%ebp), %ecx	# %sfp,\n\t"
"	movl	LCSP, %edi	# LCSP,\n\t"
"	movl	%eax, -56(%ebp)	#, %sfp\n\t"
"	movl	%eax, LCSS	#, LCSS\n\t"
"	movzbl	a(%edx), %eax	# a, tmp131\n\t"
"	cmpb	b(%esi), %al	# b, tmp131\n\t"
"	movl	%edi, -52(%ebp)	#, %sfp\n\t"
"	sete	%al	#, tmp132\n\t"
"	subl	$1, %ecx	#,\n\t"
"	cmpl	$1, -72(%ebp)	#, %sfp\n\t"
"	movzbl	%al, %eax	# tmp132, tmp133\n\t"
"	movl	%eax, (%edi)	# tmp133,\n\t"
"	movl	%ecx, -96(%ebp)	#, %sfp\n\t"
"	jle	.L9	#,\n\t"
"	movl	-96(%ebp), %edi	# %sfp, D.9623\n\t"
"	movl	%edx, %ecx	#, ivtmp.194\n\t"
"	xorl	%eax, %eax	# ivtmp.196\n\t"
"	addl	$a+1, %ecx	#, ivtmp.194\n\t"
"	sall	$2, %edi	#, D.9623\n\t"
"	movl	%edi, -44(%ebp)	# D.9623, %sfp\n\t"
"	movl	-52(%ebp), %edi	# %sfp, __b\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L12:\n\t"
"	movzbl	(%ecx), %edx	# a, tmp137\n\t"
"	xorl	%ebx, %ebx	# D.9447\n\t"
"	cmpb	b(%esi), %dl	# b, tmp137\n\t"
"	sete	%bl	#, D.9447\n\t"
"	movl	%ebx, -28(%ebp)	# D.9447, D.9046\n\t"
"	movl	(%edi,%eax), %edx	#* ivtmp.196, D.9447\n\t"
"	cmpl	%edx, %ebx	# D.9447, D.9447\n\t"
"	jle	.L11	#,\n\t"
"	movl	%ebx, %edx	# D.9447, D.9447\n\t"
".L11:\n\t"
"	movl	%edx, 4(%edi,%eax)	# D.9447,\n\t"
"	addl	$1, %ecx	#, ivtmp.194\n\t"
"	addl	$4, %eax	#, ivtmp.196\n\t"
"	cmpl	-44(%ebp), %eax	# %sfp, ivtmp.196\n\t"
"	jne	.L12	#,\n\t"
".L9:\n\t"
"	movl	20(%ebp), %edx	# KB, tmp140\n\t"
"	movl	$2, %ecx	#, tmp143\n\t"
"	leal	1(%esi), %edi	#, i\n\t"
"	addl	%esi, %edx	# PB, tmp140\n\t"
"	movl	%edx, %eax	# tmp140,\n\t"
"	sarl	$31, %edx	#, tmp142\n\t"
"	idivl	%ecx	# tmp143\n\t"
"	cmpl	%eax, %edi	#, i\n\t"
"	movl	%eax, -92(%ebp)	#, %sfp\n\t"
"	jge	.L13	#,\n\t"
"	movl	8(%ebp), %edx	# PA,\n\t"
"	addl	$b, %eax	#,\n\t"
"	addl	$b, %edi	#, ivtmp.187\n\t"
"	movl	%eax, -60(%ebp)	#, %sfp\n\t"
"	addl	$a+1, %edx	#,\n\t"
"	movl	%edx, -68(%ebp)	#, %sfp\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L20:\n\t"
"	movl	8(%ebp), %ebx	# PA,\n\t"
"	movzbl	(%edi), %eax	# b, tmp145\n\t"
"	movl	-52(%ebp), %ecx	# %sfp,\n\t"
"	cmpb	a(%ebx), %al	# a, tmp145\n\t"
"	movl	(%ecx), %esi	#, x\n\t"
"	sete	%al	#, tmp146\n\t"
"	movzbl	%al, %eax	# tmp146, D.9445\n\t"
"	movl	%eax, -32(%ebp)	# D.9445, D.9048\n\t"
"	movl	(%ecx), %edx	#, tmp148\n\t"
"	cmpl	%edx, %eax	# tmp148, D.9445\n\t"
"	jge	.L14	#,\n\t"
"	movl	%edx, %eax	# tmp148, D.9445\n\t"
".L14:\n\t"
"	movl	-52(%ebp), %edx	# %sfp,\n\t"
"	cmpl	$1, -72(%ebp)	#, %sfp\n\t"
"	movl	%eax, (%edx)	# D.9445,\n\t"
"	jle	.L15	#,\n\t"
"	movl	-68(%ebp), %ecx	# %sfp, ivtmp.182\n\t"
"	movl	$4, %eax	#, ivtmp.180\n\t"
"	movl	%esi, -44(%ebp)	# x, %sfp\n\t"
"	movl	%ecx, -64(%ebp)	# ivtmp.182, %sfp\n\t"
"	jmp	.L19	#\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L16:\n\t"
"	movl	-52(%ebp), %ecx	# %sfp,\n\t"
"	movl	%edx, %esi	# q.203, iftmp.29\n\t"
"	movl	-4(%ecx,%eax), %ecx	#,\n\t"
"	cmpl	%ecx, %edx	#, q.203\n\t"
"	jge	.L17	#,\n\t"
"	movl	%ecx, %esi	#, iftmp.29\n\t"
".L17:\n\t"
"	addl	$4, %eax	#, ivtmp.180\n\t"
"	addl	$1, -64(%ebp)	#, %sfp\n\t"
"	cmpl	%eax, -48(%ebp)	# ivtmp.180, %sfp\n\t"
"	movl	%esi, (%ebx)	# iftmp.29,* __b\n\t"
"	movl	%edx, -44(%ebp)	# q.203, %sfp\n\t"
"	je	.L15	#,\n\t"
".L19:\n\t"
"	movl	-52(%ebp), %ebx	# %sfp, __b\n\t"
"	movl	-64(%ebp), %esi	# %sfp,\n\t"
"	movzbl	(%edi), %ecx	# b,\n\t"
"	addl	%eax, %ebx	# ivtmp.180, __b\n\t"
"	cmpb	(%esi), %cl	# a,\n\t"
"	movl	(%ebx), %edx	#* __b, q.203\n\t"
"	jne	.L16	#,\n\t"
"	movl	-44(%ebp), %esi	# %sfp, iftmp.29\n\t"
"	addl	$1, %esi	#, iftmp.29\n\t"
"	jmp	.L17	#\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L15:\n\t"
"	addl	$1, %edi	#, ivtmp.187\n\t"
"	cmpl	-60(%ebp), %edi	# %sfp, ivtmp.187\n\t"
"	jne	.L20	#,\n\t"
".L13:\n\t"
"	movl	12(%ebp), %edi	# KA,\n\t"
"	movl	12(%ebp), %edx	# KA,\n\t"
"	movl	-96(%ebp), %ebx	# %sfp,\n\t"
"	movl	20(%ebp), %ecx	# KB,\n\t"
"	subl	$1, %edi	#,\n\t"
"	movl	-56(%ebp), %esi	# %sfp,\n\t"
"	movl	%edi, -88(%ebp)	#, %sfp\n\t"
"	movl	20(%ebp), %edi	# KB, D.9152\n\t"
"	sall	$2, %ebx	#,\n\t"
"	movzbl	a-1(%edx), %eax	# a, tmp155\n\t"
"	movl	%ebx, -84(%ebp)	#, %sfp\n\t"
"	addl	%ebx, %esi	#,\n\t"
"	movl	-72(%ebp), %ebx	# %sfp,\n\t"
"	subl	$1, %edi	#, D.9152\n\t"
"	cmpb	b-1(%ecx), %al	# b, tmp155\n\t"
"	movl	%esi, -60(%ebp)	#, %sfp\n\t"
"	sete	%al	#, tmp156\n\t"
"	subl	$2, %ebx	#,\n\t"
"	movzbl	%al, %eax	# tmp156, tmp157\n\t"
"	movl	%eax, (%esi)	# tmp157,\n\t"
"	movl	%ebx, -68(%ebp)	#, %sfp\n\t"
"	js	.L21	#,\n\t"
"	movl	8(%ebp), %esi	# PA,\n\t"
"	movl	-72(%ebp), %eax	# %sfp,\n\t"
"	movl	-68(%ebp), %edx	# %sfp,\n\t"
"	movl	%edi, -44(%ebp)	# D.9152, %sfp\n\t"
"	leal	a-2(%eax,%esi), %ebx	#, ivtmp.170\n\t"
"	movl	-56(%ebp), %esi	# %sfp,\n\t"
"	leal	(%esi,%edx,4), %ecx	#, ivtmp.175\n\t"
"	movl	-84(%ebp), %esi	# %sfp, ivtmp.217\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L24:\n\t"
"	movl	-44(%ebp), %edi	# %sfp,\n\t"
"	xorl	%edx, %edx	# D.9441\n\t"
"	movzbl	(%ebx), %eax	# a, tmp162\n\t"
"	cmpb	b(%edi), %al	# b, tmp162\n\t"
"	movl	-56(%ebp), %edi	# %sfp,\n\t"
"	sete	%dl	#, D.9441\n\t"
"	movl	%edx, -36(%ebp)	# D.9441, D.9051\n\t"
"	movl	(%edi,%esi), %eax	#* ivtmp.217, D.9441\n\t"
"	cmpl	%edx, %eax	# D.9441, D.9441\n\t"
"	jge	.L23	#,\n\t"
"	movl	%edx, %eax	# D.9441, D.9441\n\t"
".L23:\n\t"
"	movl	%eax, (%ecx)	# D.9441,* ivtmp.175\n\t"
"	subl	$1, %ebx	#, ivtmp.170\n\t"
"	subl	$4, %ecx	#, ivtmp.175\n\t"
"	subl	$4, %esi	#, ivtmp.217\n\t"
"	jne	.L24	#,\n\t"
".L21:\n\t"
"	movl	20(%ebp), %eax	# KB, i\n\t"
"	subl	$2, %eax	#, i\n\t"
"	cmpl	-92(%ebp), %eax	# %sfp, i\n\t"
"	jl	.L25	#,\n\t"
"	addl	$b, %eax	#,\n\t"
"	movl	-68(%ebp), %edx	# %sfp,\n\t"
"	movl	%eax, -48(%ebp)	#, %sfp\n\t"
"	movl	-72(%ebp), %ebx	# %sfp,\n\t"
"	movl	-92(%ebp), %eax	# %sfp,\n\t"
"	movl	8(%ebp), %ecx	# PA,\n\t"
"	sall	$2, %edx	#,\n\t"
"	movl	%edx, -80(%ebp)	#, %sfp\n\t"
"	addl	$b-1, %eax	#,\n\t"
"	leal	a-2(%ebx,%ecx), %ecx	#,\n\t"
"	movl	%eax, -76(%ebp)	#, %sfp\n\t"
"	movl	%ecx, -64(%ebp)	#, %sfp\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L32:\n\t"
"	movl	-48(%ebp), %esi	# %sfp,\n\t"
"	movl	-88(%ebp), %edx	# %sfp,\n\t"
"	movl	-60(%ebp), %ebx	# %sfp,\n\t"
"	movzbl	(%esi), %eax	# b, tmp166\n\t"
"	cmpb	a(%edx), %al	# a, tmp166\n\t"
"	movl	(%ebx), %edi	#, x.204\n\t"
"	sete	%al	#, tmp167\n\t"
"	movzbl	%al, %eax	# tmp167, D.9439\n\t"
"	movl	%eax, -40(%ebp)	# D.9439, D.9053\n\t"
"	movl	(%ebx), %edx	#, tmp169\n\t"
"	cmpl	%edx, %eax	# tmp169, D.9439\n\t"
"	jge	.L26	#,\n\t"
"	movl	%edx, %eax	# tmp169, D.9439\n\t"
".L26:\n\t"
"	movl	-60(%ebp), %ecx	# %sfp,\n\t"
"	movl	%eax, (%ecx)	# D.9439,\n\t"
"	movl	-68(%ebp), %eax	# %sfp,\n\t"
"	testl	%eax, %eax	#\n\t"
"	js	.L27	#,\n\t"
"	movl	-64(%ebp), %ecx	# %sfp, ivtmp.151\n\t"
"	movl	-80(%ebp), %eax	# %sfp, ivtmp.149\n\t"
"	movl	-84(%ebp), %esi	# %sfp, ivtmp.215\n\t"
"	movl	%edi, -44(%ebp)	# x.204, %sfp\n\t"
"	movl	%ecx, -92(%ebp)	# ivtmp.151, %sfp\n\t"
"	jmp	.L31	#\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L28:\n\t"
"	movl	-56(%ebp), %ecx	# %sfp,\n\t"
"	movl	%edx, %edi	# q.209, iftmp.40\n\t"
"	movl	(%ecx,%esi), %ecx	#* ivtmp.215,\n\t"
"	cmpl	%ecx, %edx	#, q.209\n\t"
"	jge	.L29	#,\n\t"
"	movl	%ecx, %edi	#, iftmp.40\n\t"
".L29:\n\t"
"	subl	$4, %eax	#, ivtmp.149\n\t"
"	subl	$4, %esi	#, ivtmp.215\n\t"
"	subl	$1, -92(%ebp)	#, %sfp\n\t"
"	cmpl	$-4, %eax	#, ivtmp.149\n\t"
"	movl	%edi, (%ebx)	# iftmp.40,* __b\n\t"
"	movl	%edx, -44(%ebp)	# q.209, %sfp\n\t"
"	je	.L27	#,\n\t"
".L31:\n\t"
"	movl	-48(%ebp), %ecx	# %sfp,\n\t"
"	movl	-56(%ebp), %ebx	# %sfp, __b\n\t"
"	movl	-92(%ebp), %edi	# %sfp,\n\t"
"	movzbl	(%ecx), %ecx	# b,\n\t"
"	addl	%eax, %ebx	# ivtmp.149, __b\n\t"
"	cmpb	(%edi), %cl	# a,\n\t"
"	movl	(%ebx), %edx	#* __b, q.209\n\t"
"	jne	.L28	#,\n\t"
"	movl	-44(%ebp), %edi	# %sfp, iftmp.40\n\t"
"	addl	$1, %edi	#, iftmp.40\n\t"
"	jmp	.L29	#\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L27:\n\t"
"	subl	$1, -48(%ebp)	#, %sfp\n\t"
"	movl	-76(%ebp), %ebx	# %sfp,\n\t"
"	cmpl	%ebx, -48(%ebp)	#, %sfp\n\t"
"	jne	.L32	#,\n\t"
".L25:\n\t"
"	movl	-56(%ebp), %esi	# %sfp,\n\t"
"	cmpl	$1, -72(%ebp)	#, %sfp\n\t"
"	movl	(%esi), %ecx	#, q.212\n\t"
"	jle	.L33	#,\n\t"
"	movl	$1, %eax	#, ivtmp.140\n\t"
".L35:\n\t"
"	movl	-56(%ebp), %edi	# %sfp,\n\t"
"	movl	-52(%ebp), %ebx	# %sfp,\n\t"
"	movl	(%edi,%eax,4), %edx	#, tmp174\n\t"
"	addl	-4(%ebx,%eax,4), %edx	#, tmp174\n\t"
"	cmpl	%edx, %ecx	# tmp174, q.212\n\t"
"	jge	.L34	#,\n\t"
"	movl	%edx, %ecx	# tmp174, q.212\n\t"
".L34:\n\t"
"	addl	$1, %eax	#, ivtmp.140\n\t"
"	cmpl	%eax, -72(%ebp)	# ivtmp.140, %sfp\n\t"
"	jne	.L35	#,\n\t"
".L33:\n\t"
"	movl	-96(%ebp), %esi	# %sfp,\n\t"
"	movl	%ecx, %ebx	# q.212, q\n\t"
"	movl	-52(%ebp), %edi	# %sfp,\n\t"
"	movl	(%edi,%esi,4), %eax	#, tmp177\n\t"
"	cmpl	%eax, %ecx	# tmp177, q\n\t"
"	jge	.L36	#,\n\t"
"	movl	%eax, %ebx	# tmp177, q\n\t"
".L36:\n\t"
"	movl	-52(%ebp), %eax	# %sfp,\n\t"
"	movl	%eax, (%esp)	#,\n\t"
"	call	_ZdaPv	#\n\t"
"	movl	LCSS, %eax	# LCSS, LCSS.31\n\t"
"	testl	%eax, %eax	# LCSS.31\n\t"
"	je	.L7	#,\n\t"
"	movl	%eax, (%esp)	# LCSS.31,\n\t"
"	call	_ZdaPv	#\n\t"
"	jmp	.L7	#\n\t"
".L49:\n\t"
"	movl	12(%ebp), %eax	# KA,\n\t"
"	cmpl	%eax, 8(%ebp)	#, PA\n\t"
"	.p2align 4,,2\n\t"
"	jge	.L3	#,\n\t"
"	movl	8(%ebp), %edx	# PA,\n\t"
"	movzbl	b(%esi), %ecx	# b, D.9067\n\t"
"	cmpb	%cl, a(%edx)	# D.9067, a\n\t"
"	je	.L4	#,\n\t"
"	movl	8(%ebp), %edx	# PA, ivtmp.136\n\t"
"	movl	8(%ebp), %eax	# PA, i\n\t"
"	addl	$a+1, %edx	#, ivtmp.136\n\t"
"	jmp	.L6	#\n\t"
".L8:\n\t"
"	movzbl	(%edx), %ebx	# a, temp.199\n\t"
"	addl	$1, %edx	#, ivtmp.136\n\t"
"	cmpb	%bl, %cl	# temp.199, D.9067\n\t"
"	je	.L4	#,\n\t"
".L6:\n\t"
"	addl	$1, %eax	#, i\n\t"
"	cmpl	%eax, 12(%ebp)	# i, KA\n\t"
"	jg	.L8	#,\n\t"
"	jmp	.L3	#\n\t"
".L4:\n\t"
"	movsbl	%cl,%ecx	# D.9067, D.9067\n\t"
"	movl	$1, %ebx	#, q\n\t"
"	movl	%ecx, (%esp)	# D.9067,\n\t"
"	call	putchar	#\n\t"
"	.p2align 4,,2\n\t"
"	jmp	.L7	#\n\t"
"	.cfi_endproc\n\t"
".LFE400:\n\t"
"	.size	_Z3LCSiiii, .-_Z3LCSiiii\n\t"
"	.section	.rodata.str1.1,\"aMS\",@progbits,1\n\t"
".LC0:\n\t"
"	.string	\"%d\\n\"\n\t"
".LC1:\n\t"
"	.string	\"%s %s\\n\"\n\t"
"	.text\n\t"
"	.p2align 4,,15\n\t"
".globl main\n\t"
"	.type	main, @function\n\t"
"main:\n\t"
".LFB401:\n\t"
"	.cfi_startproc\n\t"
"	.cfi_personality 0x0,__gxx_personality_v0\n\t"
"	pushl	%ebp	#\n\t"
"	.cfi_def_cfa_offset 8\n\t"
"	movl	%esp, %ebp	#,\n\t"
"	.cfi_offset 5, -8\n\t"
"	.cfi_def_cfa_register 5\n\t"
"	andl	$-16, %esp	#,\n\t"
"	pushl	%edi	#\n\t"
"	pushl	%esi	#\n\t"
"	pushl	%ebx	#\n\t"
"	subl	$132, %esp	#,\n\t"
"	leal	124(%esp), %eax	#, tmp111\n\t"
"	movl	%eax, 4(%esp)	# tmp111,\n\t"
"	movl	$.LC0, (%esp)	#,\n\t"
"	.cfi_escape 0x10,0x3,0x7,0x55,0x9,0xf0,0x1a,0x9,0xf4,0x22\n\t"
"	.cfi_escape 0x10,0x6,0x7,0x55,0x9,0xf0,0x1a,0x9,0xf8,0x22\n\t"
"	.cfi_escape 0x10,0x7,0x7,0x55,0x9,0xf0,0x1a,0x9,0xfc,0x22\n\t"
"	call	scanf	#\n\t"
"	jmp	.L52	#\n\t"
".L53:\n\t"
"	cmpl	$0, 76(%esp)	#, %sfp\n\t"
"	jne	.L100	#,\n\t"
".L54:\n\t"
"	movl	$45, (%esp)	#,\n\t"
"	.p2align 4,,6\n\t"
"	call	putchar	#\n\t"
".L58:\n\t"
"	movl	$10, (%esp)	#,\n\t"
"	call	putchar	#\n\t"
".L52:\n\t"
"	movl	124(%esp), %eax	# z, z.45\n\t"
"	testl	%eax, %eax	# z.45\n\t"
"	je	.L101	#,\n\t"
"	subl	$1, %eax	#, tmp112\n\t"
"	movl	$a, %edi	#, tmp113\n\t"
"	movl	%eax, 124(%esp)	# tmp112, z\n\t"
"	movl	$b, 8(%esp)	#,\n\t"
"	movl	$a, 4(%esp)	#,\n\t"
"	movl	$.LC1, (%esp)	#,\n\t"
"	call	scanf	#\n\t"
"	orl	$-1, %edx	#, tmp117\n\t"
"	xorl	%eax, %eax	# tmp118\n\t"
"	movl	%edx, %ecx	# tmp117, tmp115\n\t"
"	repnz scasb\n\t"
"	movl	$b, %edi	#, tmp119\n\t"
"	notl	%ecx	# tmp115\n\t"
"	subl	$1, %ecx	#,\n\t"
"	movl	%ecx, 76(%esp)	#, %sfp\n\t"
"	movl	%ecx, n	#, n\n\t"
"	movl	%edx, %ecx	# tmp117,\n\t"
"	repnz scasb\n\t"
"	movl	%ecx, %edx	#, tmp121\n\t"
"	notl	%edx	# tmp121\n\t"
"	subl	$1, %edx	#,\n\t"
"	cmpl	$1, %edx	#,\n\t"
"	movl	%edx, 80(%esp)	#, %sfp\n\t"
"	movl	%edx, m	#, m\n\t"
"	jne	.L53	#,\n\t"
"	cmpl	$0, 76(%esp)	#, %sfp\n\t"
"	jle	.L54	#,\n\t"
"	movzbl	b, %edx	# b, temp.362\n\t"
"	xorl	%eax, %eax	# i\n\t"
"	cmpb	%dl, a	# temp.362, a\n\t"
"	je	.L55	#,\n\t"
".L57:\n\t"
"	addl	$1, %eax	#, i\n\t"
"	cmpl	%eax, 76(%esp)	# i, %sfp\n\t"
"	jle	.L54	#,\n\t"
"	cmpb	%dl, a(%eax)	# temp.362, a\n\t"
"	jne	.L57	#,\n\t"
".L55:\n\t"
"	movsbl	%dl,%edx	# temp.362, temp.362\n\t"
"	movl	%edx, (%esp)	# temp.362,\n\t"
"	call	putchar	#\n\t"
"	jmp	.L58	#\n\t"
".L100:\n\t"
"	movl	76(%esp), %ebx	# %sfp, D.9673\n\t"
"	sall	$2, %ebx	#, D.9673\n\t"
"	movl	%ebx, (%esp)	# D.9673,\n\t"
"	call	_Znaj	#\n\t"
"	movl	%ebx, (%esp)	# D.9673,\n\t"
"	movl	%eax, LCSP	# D.9674, LCSP\n\t"
"	call	_Znaj	#\n\t"
"	movl	LCSP, %ebx	# LCSP,\n\t"
"	movl	%ebx, 88(%esp)	#, %sfp\n\t"
"	movl	%eax, 84(%esp)	#, %sfp\n\t"
"	movl	%eax, LCSS	#, LCSS\n\t"
"	movzbl	a, %eax	# a, a\n\t"
"	cmpb	b, %al	# b, a\n\t"
"	sete	%al	#, tmp132\n\t"
"	cmpl	$1, 76(%esp)	#, %sfp\n\t"
"	movzbl	%al, %eax	# tmp132, tmp133\n\t"
"	movl	%eax, (%ebx)	# tmp133,\n\t"
"	jle	.L60	#,\n\t"
"	movl	88(%esp), %esi	# %sfp, __b\n\t"
"	xorl	%ebx, %ebx	# ivtmp.352\n\t"
"	movl	$1, %eax	#, i\n\t"
"	movl	76(%esp), %edi	# %sfp, D.9249\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L63:\n\t"
"	movzbl	a(%eax), %edx	# a, tmp136\n\t"
"	xorl	%ecx, %ecx	# D.9789\n\t"
"	cmpb	b, %dl	# b, tmp136\n\t"
"	sete	%cl	#, D.9789\n\t"
"	movl	%ecx, 120(%esp)	# D.9789, D.9686\n\t"
"	movl	(%esi,%ebx), %edx	#* ivtmp.352, D.9789\n\t"
"	cmpl	%ecx, %edx	# D.9789, D.9789\n\t"
"	jge	.L62	#,\n\t"
"	movl	%ecx, %edx	# D.9789, D.9789\n\t"
".L62:\n\t"
"	movl	%edx, (%esi,%eax,4)	# D.9789,* __b\n\t"
"	addl	$1, %eax	#, i\n\t"
"	addl	$4, %ebx	#, ivtmp.352\n\t"
"	cmpl	%eax, %edi	# i, D.9249\n\t"
"	jne	.L63	#,\n\t"
".L60:\n\t"
"	movl	80(%esp), %edx	# %sfp,\n\t"
"	movl	$2, %ecx	#, tmp141\n\t"
"	movl	%edx, %eax	#,\n\t"
"	sarl	$31, %edx	#,\n\t"
"	idivl	%ecx	# tmp141\n\t"
"	cmpl	$1, %eax	#,\n\t"
"	movl	%eax, 68(%esp)	#, %sfp\n\t"
"	jle	.L64	#,\n\t"
"	movl	$1, %edi	#, i\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L71:\n\t"
"	movzbl	b(%edi), %eax	# b, tmp144\n\t"
"	cmpb	a, %al	# a, tmp144\n\t"
"	movl	88(%esp), %ecx	# %sfp,\n\t"
"	sete	%al	#, tmp145\n\t"
"	movzbl	%al, %eax	# tmp145, D.9787\n\t"
"	movl	(%ecx), %esi	#, x\n\t"
"	movl	%eax, 116(%esp)	# D.9787, D.9696\n\t"
"	movl	(%ecx), %edx	#, tmp147\n\t"
"	cmpl	%edx, %eax	# tmp147, D.9787\n\t"
"	jge	.L65	#,\n\t"
"	movl	%edx, %eax	# tmp147, D.9787\n\t"
".L65:\n\t"
"	movl	88(%esp), %ebx	# %sfp,\n\t"
"	cmpl	$1, 76(%esp)	#, %sfp\n\t"
"	movl	%eax, (%ebx)	# D.9787,\n\t"
"	jle	.L66	#,\n\t"
"	xorl	%ebx, %ebx	# ivtmp.339\n\t"
"	movl	$1, %eax	#, j\n\t"
"	movl	%ebx, 72(%esp)	# ivtmp.339, %sfp\n\t"
"	jmp	.L70	#\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L67:\n\t"
"	movl	88(%esp), %ebx	# %sfp,\n\t"
"	movl	72(%esp), %esi	# %sfp,\n\t"
"	movl	(%ebx,%esi), %esi	#,\n\t"
"	movl	%esi, 92(%esp)	#, %sfp\n\t"
"	movl	%edx, %esi	# x.357, iftmp.29\n\t"
"	cmpl	92(%esp), %edx	# %sfp, x.357\n\t"
"	jge	.L68	#,\n\t"
"	movl	92(%esp), %esi	# %sfp, iftmp.29\n\t"
".L68:\n\t"
"	addl	$1, %eax	#, j\n\t"
"	addl	$4, 72(%esp)	#, %sfp\n\t"
"	cmpl	%eax, 76(%esp)	# j, %sfp\n\t"
"	movl	%esi, (%ecx)	# iftmp.29,* __b\n\t"
"	je	.L66	#,\n\t"
".L102:\n\t"
"	movl	%edx, %esi	# x.357, x\n\t"
".L70:\n\t"
"	movl	88(%esp), %edx	# %sfp,\n\t"
"	movzbl	b(%edi), %ebx	# b,\n\t"
"	cmpb	a(%eax), %bl	# a,\n\t"
"	leal	(%edx,%eax,4), %ecx	#, __b\n\t"
"	movl	(%ecx), %edx	#* __b, x.357\n\t"
"	jne	.L67	#,\n\t"
"	addl	$1, %esi	#, iftmp.29\n\t"
"	addl	$1, %eax	#, j\n\t"
"	addl	$4, 72(%esp)	#, %sfp\n\t"
"	cmpl	%eax, 76(%esp)	# j, %sfp\n\t"
"	movl	%esi, (%ecx)	# iftmp.29,* __b\n\t"
"	jne	.L102	#,\n\t"
".L66:\n\t"
"	addl	$1, %edi	#, i\n\t"
"	cmpl	68(%esp), %edi	# %sfp, i\n\t"
"	jne	.L71	#,\n\t"
".L64:\n\t"
"	movl	76(%esp), %edi	# %sfp,\n\t"
"	movl	84(%esp), %eax	# %sfp,\n\t"
"	movl	76(%esp), %ebx	# %sfp,\n\t"
"	subl	$1, %edi	#,\n\t"
"	movl	%edi, 64(%esp)	#, %sfp\n\t"
"	sall	$2, %edi	#,\n\t"
"	movl	64(%esp), %edx	# %sfp,\n\t"
"	addl	%edi, %eax	#,\n\t"
"	movl	%edi, 56(%esp)	#, %sfp\n\t"
"	movl	80(%esp), %edi	# %sfp, D.9717\n\t"
"	movl	%eax, 72(%esp)	#, %sfp\n\t"
"	movl	72(%esp), %ecx	# %sfp,\n\t"
"	movzbl	a(%edx), %eax	# a, tmp156\n\t"
"	subl	$1, %edi	#, D.9717\n\t"
"	cmpb	b(%edi), %al	# b, tmp156\n\t"
"	sete	%al	#, tmp157\n\t"
"	subl	$2, %ebx	#,\n\t"
"	movzbl	%al, %eax	# tmp157, tmp158\n\t"
"	movl	%eax, (%ecx)	# tmp158,\n\t"
"	movl	%ebx, 60(%esp)	#, %sfp\n\t"
"	js	.L72	#,\n\t"
"	movl	56(%esp), %ebx	# %sfp, ivtmp.373\n\t"
"	xorl	%eax, %eax	# ivtmp.326\n\t"
"	movl	76(%esp), %esi	# %sfp, D.9249\n\t"
"	movl	%edi, 92(%esp)	# D.9717, %sfp\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L75:\n\t"
"	movl	92(%esp), %edi	# %sfp,\n\t"
"	xorl	%ecx, %ecx	# D.9783\n\t"
"	movzbl	a-2(%esi,%eax), %edx	# a, tmp161\n\t"
"	cmpb	b(%edi), %dl	# b, tmp161\n\t"
"	movl	84(%esp), %edi	# %sfp,\n\t"
"	leal	(%eax,%esi), %edx	#,\n\t"
"	movl	%edx, 52(%esp)	#, %sfp\n\t"
"	sete	%cl	#, D.9783\n\t"
"	movl	%ecx, 112(%esp)	# D.9783, D.9722\n\t"
"	movl	(%edi,%ebx), %edx	#* ivtmp.373, D.9783\n\t"
"	cmpl	%ecx, %edx	# D.9783, D.9783\n\t"
"	jge	.L74	#,\n\t"
"	movl	84(%esp), %edi	# %sfp,\n\t"
"	movl	%ecx, %edx	# D.9783, D.9783\n\t"
".L74:\n\t"
"	movl	52(%esp), %ecx	# %sfp,\n\t"
"	subl	$1, %eax	#, ivtmp.326\n\t"
"	subl	$4, %ebx	#, ivtmp.373\n\t"
"	movl	%edx, -8(%edi,%ecx,4)	# D.9783,\n\t"
"	jne	.L75	#,\n\t"
".L72:\n\t"
"	movl	80(%esp), %eax	# %sfp, i\n\t"
"	subl	$2, %eax	#, i\n\t"
"	cmpl	68(%esp), %eax	# %sfp, i\n\t"
"	jl	.L76	#,\n\t"
"	addl	$b, %eax	#,\n\t"
"	movl	60(%esp), %edx	# %sfp,\n\t"
"	movl	%eax, 80(%esp)	#, %sfp\n\t"
"	movl	60(%esp), %ecx	# %sfp,\n\t"
"	movl	68(%esp), %eax	# %sfp,\n\t"
"	sall	$2, %edx	#,\n\t"
"	addl	$a, %ecx	#,\n\t"
"	addl	$b-1, %eax	#,\n\t"
"	movl	%eax, 68(%esp)	#, %sfp\n\t"
"	movl	%edx, 52(%esp)	#, %sfp\n\t"
"	movl	%ecx, 48(%esp)	#, %sfp\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L83:\n\t"
"	movl	80(%esp), %esi	# %sfp,\n\t"
"	movl	64(%esp), %edx	# %sfp,\n\t"
"	movl	72(%esp), %ebx	# %sfp,\n\t"
"	movzbl	(%esi), %eax	# b, tmp166\n\t"
"	cmpb	a(%edx), %al	# a, tmp166\n\t"
"	movl	(%ebx), %edi	#, x.358\n\t"
"	sete	%al	#, tmp167\n\t"
"	movzbl	%al, %eax	# tmp167, D.9781\n\t"
"	movl	%eax, 108(%esp)	# D.9781, D.9730\n\t"
"	movl	(%ebx), %edx	#, tmp169\n\t"
"	cmpl	%edx, %eax	# tmp169, D.9781\n\t"
"	jge	.L77	#,\n\t"
"	movl	%edx, %eax	# tmp169, D.9781\n\t"
".L77:\n\t"
"	movl	60(%esp), %edx	# %sfp,\n\t"
"	movl	72(%esp), %ecx	# %sfp,\n\t"
"	testl	%edx, %edx	#\n\t"
"	movl	%eax, (%ecx)	# D.9781,\n\t"
"	js	.L78	#,\n\t"
"	movl	48(%esp), %ecx	# %sfp, ivtmp.309\n\t"
"	movl	%edi, 92(%esp)	# x.358, %sfp\n\t"
"	movl	52(%esp), %eax	# %sfp, ivtmp.307\n\t"
"	movl	56(%esp), %esi	# %sfp, ivtmp.371\n\t"
"	movl	%ecx, 28(%esp)	# ivtmp.309, %sfp\n\t"
"	movl	%ecx, %edi	# ivtmp.309,\n\t"
"	jmp	.L82	#\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L79:\n\t"
"	movl	84(%esp), %ecx	# %sfp,\n\t"
"	movl	%edx, %edi	# x.365, iftmp.40\n\t"
"	movl	(%ecx,%esi), %ecx	#* ivtmp.371,\n\t"
"	cmpl	%ecx, %edx	#, x.365\n\t"
"	movl	%ecx, 92(%esp)	#, %sfp\n\t"
"	jge	.L80	#,\n\t"
"	movl	%ecx, %edi	#, iftmp.40\n\t"
".L80:\n\t"
"	subl	$4, %eax	#, ivtmp.307\n\t"
"	subl	$4, %esi	#, ivtmp.371\n\t"
"	subl	$1, 28(%esp)	#, %sfp\n\t"
"	cmpl	$-4, %eax	#, ivtmp.307\n\t"
"	movl	%edi, (%ebx)	# iftmp.40,* __b\n\t"
"	je	.L78	#,\n\t"
"	movl	28(%esp), %edi	# %sfp,\n\t"
"	movl	%edx, 92(%esp)	# x.365, %sfp\n\t"
".L82:\n\t"
"	movl	80(%esp), %ecx	# %sfp,\n\t"
"	movl	84(%esp), %ebx	# %sfp, __b\n\t"
"	movzbl	(%ecx), %ecx	# b,\n\t"
"	addl	%eax, %ebx	# ivtmp.307, __b\n\t"
"	cmpb	(%edi), %cl	# a,\n\t"
"	movl	(%ebx), %edx	#* __b, x.365\n\t"
"	jne	.L79	#,\n\t"
"	movl	92(%esp), %edi	# %sfp, iftmp.40\n\t"
"	addl	$1, %edi	#, iftmp.40\n\t"
"	jmp	.L80	#\n\t"
"	.p2align 4,,7\n\t"
"	.p2align 3\n\t"
".L78:\n\t"
"	subl	$1, 80(%esp)	#, %sfp\n\t"
"	movl	68(%esp), %ebx	# %sfp,\n\t"
"	cmpl	%ebx, 80(%esp)	#, %sfp\n\t"
"	jne	.L83	#,\n\t"
".L76:\n\t"
"	movl	84(%esp), %esi	# %sfp,\n\t"
"	cmpl	$0, 64(%esp)	#, %sfp\n\t"
"	movl	(%esi), %ebx	#, q\n\t"
"	jle	.L84	#,\n\t"
"	movl	$1, %eax	#, ivtmp.298\n\t"
".L86:\n\t"
"	movl	84(%esp), %edi	# %sfp,\n\t"
"	movl	88(%esp), %ecx	# %sfp,\n\t"
"	movl	(%edi,%eax,4), %edx	#, tmp172\n\t"
"	addl	-4(%ecx,%eax,4), %edx	#, tmp172\n\t"
"	cmpl	%edx, %ebx	# tmp172, q\n\t"
"	jge	.L85	#,\n\t"
"	movl	%edx, %ebx	# tmp172, q\n\t"
".L85:\n\t"
"	addl	$1, %eax	#, ivtmp.298\n\t"
"	cmpl	76(%esp), %eax	# %sfp, ivtmp.298\n\t"
"	jne	.L86	#,\n\t"
".L84:\n\t"
"	movl	88(%esp), %eax	# %sfp,\n\t"
"	movl	64(%esp), %edi	# %sfp,\n\t"
"	movl	(%eax,%edi,4), %esi	#, D.9755\n\t"
"	movl	%eax, (%esp)	#,\n\t"
"	call	_ZdaPv	#\n\t"
"	movl	LCSS, %eax	# LCSS, LCSS.31\n\t"
"	testl	%eax, %eax	# LCSS.31\n\t"
"	je	.L87	#,\n\t"
"	movl	%eax, (%esp)	# LCSS.31,\n\t"
"	call	_ZdaPv	#\n\t"
".L87:\n\t"
"	cmpl	%esi, %ebx	# D.9755, q\n\t"
"	jge	.L88	#,\n\t"
"	movl	%esi, %ebx	# D.9755, q\n\t"
".L88:\n\t"
"	testl	%ebx, %ebx	# q\n\t"
"	jne	.L58	#,\n\t"
"	.p2align 4,,5\n\t"
"	jmp	.L54	#\n\t"
".L101:\n\t"
"	addl	$132, %esp	#,\n\t"
"	popl	%ebx	#\n\t"
"	popl	%esi	#\n\t"
"	popl	%edi	#\n\t"
"	movl	%ebp, %esp	#,\n\t"
"	popl	%ebp	#\n\t"
"	ret\n\t"
"	.cfi_endproc\n\t"
".LFE401:\n\t"
"	.size	main, .-main\n\t"
".globl a\n\t"
"	.bss\n\t"
"	.align 32\n\t"
"	.type	a, @object\n\t"
"	.size	a, 30005\n\t"
"a:\n\t"
"	.zero	30005\n\t"
".globl b\n\t"
"	.align 32\n\t"
"	.type	b, @object\n\t"
"	.size	b, 30005\n\t"
"b:\n\t"
"	.zero	30005\n\t"
".globl LCSP\n\t"
"	.align 4\n\t"
"	.type	LCSP, @object\n\t"
"	.size	LCSP, 4\n\t"
"LCSP:\n\t"
"	.zero	4\n\t"
".globl LCSS\n\t"
"	.align 4\n\t"
"	.type	LCSS, @object\n\t"
"	.size	LCSS, 4\n\t"
"LCSS:\n\t"
"	.zero	4\n\t"
".globl n\n\t"
"	.align 4\n\t"
"	.type	n, @object\n\t"
"	.size	n, 4\n\t"
"n:\n\t"
"	.zero	4\n\t"
".globl m\n\t"
"	.align 4\n\t"
"	.type	m, @object\n\t"
"	.size	m, 4\n\t"
"m:\n\t"
"	.zero	4\n\t"
"	.section	.comment.SUSE.OPTs,\"MS\",@progbits,1\n\t"
"	.string	\"Ospwg\"\n\t"
"	.section	.note.GNU-stack,\"\",@progbits\n\t"
);
